version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT
      - "9001:9001"    # ws if needed
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    environment:
      - TZ=UTC

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PASS=
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
